### ISSUE TITLE
Link to Vlachos & Riedel 2014 dataset is broken

### ISSUE THREAD

**Issue by boyleconnor** [Cartus/Automated-Fact-Checking-Literature#7]
https://github.com/Cartus/Automated-Fact-Checking-Resources/blob/f2d114e4f513311be27a0e8472c95aa77ad55482/README.md?plain=1#L315C9-L315C9

The [link](https://sites.google.com/site/sites/system/errors/WebspaceNotFound?path=%2Fandreasvlachos%2Fresources) to the dataset for "Fact Checking: Task definition and dataset construction" is broken (the one provided in the paper is also broken). I can't find the dataset anywhere else on the internet, could the authors please provide an updated link if possible?

**Comment by Cartus** [comment]
I am afraid that I am not able to provide the link to this dataset. This repo is attached to the survey paper. We can only collect publicly available resources on this page. If the link in the original paper is no longer available, we have nothing to do with this case.

**Comment by andreasvlachos** [comment]
Hi, apologies for not responding earlier. The links are not functioning because google sites stopped, but my publications page has links that work to dropbox: https://andreasvlachos.github.io//publications/:
https://www.dropbox.com/s/uvwbpjytogqnm68/FactChecking_LTCSS2014_release.ods?dl=0
https://www.dropbox.com/s/l0nfaezwdpu2w6r/FactChecking_LTCSS2014_release.tsv?dl=0

**Comment by Cartus** [comment]
Thanks Andreas! I am updating the link to the repo accordingly.
